# Generated by Django 4.1.5 on 2023-02-11 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('class_name', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('parent_name', models.CharField(max_length=225)),
                ('profile_pic', models.FileField(null=True, upload_to='profiles/')),
                ('parent_middle_name', models.CharField(max_length=225, null=True)),
                ('parent_last_name', models.CharField(max_length=225, null=True)),
                ('parent_number', models.IntegerField(null=True)),
                ('father_name', models.CharField(default='', max_length=225)),
                ('father_middle_name', models.CharField(max_length=225, null=True)),
                ('father_last_name', models.CharField(max_length=225, null=True)),
                ('father_dob', models.DateField(blank=True, default=datetime.datetime.now)),
                ('father_mobile_number', models.IntegerField(null=True)),
                ('father_occupation', models.CharField(default='', max_length=225)),
                ('Address', models.CharField(max_length=225, null=True)),
                ('email', models.CharField(max_length=225, null=True)),
                ('annual_income', models.IntegerField(null=True)),
                ('mother_name', models.CharField(max_length=225, null=True)),
                ('mother_middle_name', models.CharField(max_length=225, null=True)),
                ('mother_last_name', models.CharField(max_length=225, null=True)),
                ('mother_dob', models.DateField(blank=True, default=datetime.datetime.now)),
                ('mother_mobile_number', models.IntegerField(null=True)),
                ('mother_occupation', models.CharField(max_length=255, null=True)),
                ('mother_email', models.CharField(max_length=225, null=True)),
                ('qualification', models.CharField(max_length=225, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(max_length=225)),
                ('school_address', models.CharField(max_length=225)),
                ('date_registration', models.DateField()),
                ('date_expiration', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('section_name', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_pic', models.FileField(null=True, upload_to='profiles/')),
                ('registration_date', models.DateField(auto_now=True)),
                ('medium_of_education', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=225)),
                ('middle_name', models.CharField(max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225, null=True)),
                ('student_dob', models.DateField(default=datetime.datetime.now)),
                ('student_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=255, null=True)),
                ('email', models.CharField(max_length=225, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('alternate_mobile_no', models.IntegerField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('state', models.CharField(max_length=225, null=True)),
                ('city', models.CharField(max_length=225, null=True)),
                ('zip', models.CharField(max_length=225, null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('previous_school_name', models.CharField(max_length=225, null=True)),
                ('previous_school_Address', models.CharField(max_length=225, null=True)),
                ('transfer_certificate', models.FileField(upload_to='files/')),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.parent')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosstion',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('positionName', models.CharField(max_length=255)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profile_pic', models.FileField(default='', upload_to='profiles/')),
                ('staff_name', models.CharField(max_length=225)),
                ('Address', models.CharField(max_length=225)),
                ('salary', models.IntegerField(null=True)),
                ('contact_number', models.IntegerField(null=True)),
                ('email_address', models.CharField(max_length=225, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('postion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.staffposstion')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
    ]
