# Generated by Django 4.1.5 on 2023-03-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_class_is_active_alter_parent_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffPosstion',
            new_name='StaffPossition',
        ),
    ]
