# Generated by Django 4.1.5 on 2023-03-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_staffposstion_staffpossition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email_address',
            field=models.EmailField(max_length=225, null=True),
        ),
    ]
