# Generated by Django 4.1.5 on 2023-03-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_class_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(choices=[(1, 1), (2, 1), (3, 1)], null=True),
        ),
    ]
